config/routes.rb
Rails.application.routes.draw do
  # scope "(:locale)", locale: /en|de/ do

  get '/contact' => 'static#contact'
  get '/about' => 'static#about'

  resources :breeders

  resources :horses do
    member do
      get 'progeny'
    end
  end

root to: 'home#index'

end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# end

app/views/layouts/_breeder_search.html.erb
<%= form_tag breeders_path, method: :get do %>
  <p>
    <%= text_field_tag :search_name, params[:search_name] %>
    <%= submit_tag "Search Breeder By Name", :name => nil %>
  </p>
<% end %>

app/views/layouts/_footer.html.erb
<footer class='center responsive_text'>
  <p class='copyright_notice'><%= t 'shared.copyright' %> &copy; 2013-2023 Susan Prestage <%= t 'shared.and' %> Nathaniel Barnes</p>
</footer>

app/views/layouts/_header.html.erb
<div class="section-colored text-center">
  <div class="container">
    <div class="row">
      <div class"col-lg-12">
        <div id="user_header">
          <div class="nav">
            <% flash.each do |name, msg| %>
              <%= content_tag :div, msg, id: "flash_#{name}" %>
            <% end %>
          </div>
        </div>
      </div><!-- /.col -->
    </div><!-- /.row  -->
  </div><!-- /.container -->
</div>

app/views/layouts/_horse_search.html.erb
<div id="horse_search_bar">
  <%= form_tag horses_path, method: :get do %>

    <span class="horse_search_field">
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag t("sidebar.search"), :name => nil %>
    </span>

    <span class="has_image_checkbox">
      <%= check_box_tag :has_image, params[:has_image] %>
      <%= label_tag :has_image, t(" ") %>
      <span class='has_image_checkbox_label'>Has Image</span>
    </span>

  <% end %>
</div>

app/views/layouts/_language_selector.html.erb
<span class='language_selector'>
  <%= link_to_unless_current "English", locale: "en" %> |
  <%= link_to_unless_current "Deutsche", locale: "de" %>
</span>

app/views/layouts/_trakehner_logo.html.erb
<%= image_tag( "trakehnerLogoTransparent.jpg", class: "ata_logo_image", alt: "ATA brand/logo" ) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'layouts/horse_search' %>
    <%= render 'layouts/language_selector' %>
    <div class='clear_div'></div>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>

</html>